spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none

server:
  port: 8080

oauth: #just for testing
  auth:
    provider-uri: "http://localhost:8080"
    jks:
      keypass: "password"
      storepass: "password"
      alias: "oauth2"
      location: "keystore/oauth2.jks"
