spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080 #just for testing
          #jwk-set-uri: http://localhost:8080/oauth2/jwks #just for testing