spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/post?createDatabaseIfNotExist=true&serverTimezone=UTC
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
      client:
        registration:
          provider: auth
          client-id: ""
          client-secret: ""
          authorization-grant-type: client_credentials
          scope: users:read
          client-name: posts-client
        provider:
          auth:
            authorization-uri: http://localhost:8082/oauth2/auth
            token-uri: http://localhost:8080/oauth/token
            issuer-uri: http://localhost:8080

server:
  port: 8080

posts:
  user-api:
    url: 'http://localhost:8080'
    encoded-credentials: 'YWRtaW5AZW1haWwuY29tOmFkbWlu'
